### PR TITLE
fix: Support projection pushdown for RecordBatchReader provider (fixes #186)

### LINKED ISSUE #186: rust/sedona: Projecting a data frame derived from a record batch reder results in a projection error
Reprex:

```python
import pyarrow as pa
import sedona.db

sd = sedona.db.connect()

def batches():
    for i in range(10):
        yield pa.record_batch({"a":["a", "b", "c"], "b": [1, 2, 3]})

reader = pa.RecordBatchReader.from_batches(next(batches()).schema, batches())
sd.create_data_frame(reader).to_view("foofy", overwrite=True)
sd.sql("SELECT b as banana FROM foofy").show()
#> SedonaError: Input field name a does not match with the projection expression b.
```

### PR DESCRIPTION
**Pull request by Kontinuation**
This fixes #186.

The provider ignored the projection indices passed to TableProvider::scan(), so the physical plan schema ([a,b]) did not match the pushed-down logical projection ([b]). This PR implements projection pushdown for RecordBatchReaderProvider and adds a regression test.

### CODE REVIEW

File: rust/sedona/src/record_batch_reader_provider.rs [hunk 1]
```diff
@@ -383,6 +419,49 @@ mod test {
         }
     }
 
+    #[tokio::test]
+    async fn test_projection_pushdown() {
+        use arrow_array::{RecordBatch, RecordBatchIterator};
+        use arrow_schema::{DataType, Field, Schema};
+        use datafusion::prelude::col;
+        use datafusion::prelude::SessionContext;
```
Comment (paleolimbot) [inline rust/sedona/src/record_batch_reader_provider.rs]: Should these be module-level `use`s?

Comment (Kontinuation) [reply rust/sedona/src/record_batch_reader_provider.rs]: Moved these to module level.
