### PR TITLE
fix(rust/sedona-functions): Let `ST_Collect_Agg()` on a Geography return a Geography

### LINKED ISSUE #280: ST_Collect() on a Geography returns a Geometry
```python
sd.sql("SELECT ST_Collect(ST_GeogPoint(0, 1))").schema
#> SedonaSchema with 1 field:
#>   st_collect(st_geogpoint(Int64(0),Int64(1))): geometry<Wkb>
```

### PR DESCRIPTION
**Pull request by yutannihilation**
Fix #280

I guess there are more functions that need similar fix, but this only addresses `ST_Collect_Agg()`, which looks straightforward.

```
> SELECT ST_Collect_Agg(ST_GeogPoint(0, 1));
┌─────────────────────────────────────────────────┐
│ st_collect_agg(st_geogpoint(Int64(0),Int64(1))) │
│                    geography                    │
╞═════════════════════════════════════════════════╡
│ MULTIPOINT((0 1))                               │
└─────────────────────────────────────────────────┘
```

### CODE REVIEW

File: rust/sedona-functions/src/st_collect_agg.rs [hunk 1]
```diff
@@ -70,8 +70,14 @@ struct STCollectAggr {}
...
-        let matcher = ArgMatcher::new(vec![ArgMatcher::is_geometry_or_geography()], WKB_GEOMETRY);
-        matcher.match_args(args)
+        let geom_matcher = ArgMatcher::new(vec![ArgMatcher::is_geometry()], WKB_GEOMETRY);
+        let geog_matcher = ArgMatcher::new(vec![ArgMatcher::is_geography()], WKB_GEOGRAPHY);
+        for matcher in [geom_matcher, geog_matcher] {
+            if let result @ Ok(Some(_)) = matcher.match_args(args) {
+                return result;
+            }
+        }
+        Ok(None)
```
Comment (paleolimbot) [inline rust/sedona-functions/src/st_collect_agg.rs]: This is very similar to what the `SedonaAggregateUDF` does when resolving the `SedonaAccumulator` based on the input arguments.

**Comment by yutannihilation** [comment]
Thanks for the hint, I'll implement so! (Probably later this week or next year)
